In [1]:
import pandas as pd
import duckdb as db

In [22]:
colunas_pt = {
    'order_id': 'id_pedido',
    'customer_id': 'id_cliente',
    'customer_name': 'nome_cliente',
    'customer_segment': 'segmento_cliente',
    'customer_type': 'tipo_cliente',
    'first_purchase_date': 'data_primeira_compra',
    'last_purchase_date': 'data_ultima_compra',
    'product_id': 'id_produto',
    'product_name': 'nome_produto',
    'category': 'categoria',
    'sub_category': 'subcategoria',
    'brand': 'marca',
    'order_date': 'data_pedido',
    'quantity': 'quantidade',
    'unit_price': 'preco_unitario',
    'discount_pct': 'percentual_desconto',
    'sales_channel': 'canal_venda',
    'payment_method': 'metodo_pagamento',
    'sales_rep': 'representante_vendas',
    'region': 'regiao',
    'operating_expenses': 'despesas_operacionais',
    'cash_balance': 'saldo_caixa',
    'debt_balance': 'saldo_divida',
    'monthly_burn': 'gasto_mensal',
    'churn_flag': 'indicador_churn'
}
df = pd.read_csv(r'C:\Users\Nelio\Documents\GitHub\DPT-03\documents\raw\electronics_sales_raw.csv',dtype=str)
df.rename(columns=colunas_pt, inplace=True)

In [23]:
df.columns

Index(['id_pedido', 'id_cliente', 'nome_cliente', 'segmento_cliente',
       'tipo_cliente', 'data_primeira_compra', 'data_ultima_compra',
       'id_produto', 'nome_produto', 'categoria', 'subcategoria', 'marca',
       'data_pedido', 'quantidade', 'preco_unitario', 'percentual_desconto',
       'canal_venda', 'metodo_pagamento', 'representante_vendas', 'regiao',
       'despesas_operacionais', 'saldo_caixa', 'saldo_divida', 'gasto_mensal',
       'indicador_churn'],
      dtype='object')

### COLUNAS DATATIME

In [ ]:
colunas_data = ['data_primeira_compra', 'data_ultima_compra','data_pedido']
for coluna in colunas_data:
    df[coluna] = pd.to_datetime(df[coluna], errors='coerce',format='%Y-%m-%d')
df[['data_primeira_compra', 'data_ultima_compra','data_pedido']]

     data_primeira_compra data_ultima_compra data_pedido
0              2023-08-26         2024-04-24  2024-04-24
1              2023-02-26         2025-07-15  2025-07-15
2              2023-03-10         2024-01-01  2024-01-01
3              2023-10-02         2024-01-17  2024-01-17
4              2023-11-04         2024-12-17  2024-12-17
...                   ...                ...         ...
6995           2022-11-25         2025-10-06  2025-02-06
6996           2022-10-17         2025-12-10  2025-06-04
6997           2023-06-05         2025-07-22  2025-07-22
6998           2023-06-11         2025-10-28  2024-01-05
6999           2023-02-15         2025-11-18  2024-10-26

[7000 rows x 3 columns]

### COLUNAS FLOAT

In [ ]:
colunas_float = ['preco_unitario','despesas_operacionais', 'saldo_caixa', 'saldo_divida', 'gasto_mensal', 'percentual_desconto']
for coluna in colunas_float:
    df[coluna] = pd.to_numeric(df[coluna], errors='coerce')
    df[coluna] = df[coluna].replace({',': '.'}, regex=True).astype(float)
df[['preco_unitario','despesas_operacionais', 'saldo_caixa', 'saldo_divida', 'gasto_mensal', 'percentual_desconto']]
colunas_data = ['data_primeira_compra', 'data_ultima_compra','data_pedido']
for coluna in colunas_data:
    df[coluna] = pd.to_datetime(df[coluna], errors='coerce',format='%Y-%m-%d')
df[['data_primeira_compra', 'data_ultima_compra','data_pedido']]

,preco_unitario,despesas_operacionais,saldo_caixa,saldo_divida,gasto_mensal,percentual_desconto
0,109.77,239.83,14629.23,3092.03,329.57,0.05
1,350.29,81.55,8719.54,1189.63,88.62,0.15
2,643.98,244.79,9475.50,3302.27,389.89,0.15
3,844.50,304.91,12381.10,122.53,306.67,0.00
4,332.72,24.90,12661.78,2031.60,317.36,0.05
...,...,...,...,...,...,...
6995,323.90,44.92,9181.03,0.00,378.89,0.05
6996,1151.16,244.44,15611.15,2000.66,427.75,0.10
6997,37.02,143.83,17857.85,4046.86,321.57,0.10
6998,125.19,283.17,16181.14,3545.08,386.07,0.00
6999,833.29,77.62,8758.22,5578.31,437.83,0.20

### COLUNAS INTEIROS

In [ ]:
colunas_integer = ['quantidade']
for coluna in colunas_integer:
    df[coluna] = pd.to_numeric(df[coluna], errors='coerce').astype('Int64')
df[ ['quantidade']]

      quantidade
0              4
1              3
2              2
3              1
4              1
...          ...
6995           2
6996           1
6997           4
6998           3
6999           1

[7000 rows x 1 columns]

## COLUNAS TRATADAS

In [40]:
colunas_int = ['quantidade']
colunas_float = ['preco_unitario','despesas_operacionais', 'saldo_caixa', 'saldo_divida', 'gasto_mensal', 'percentual_desconto']
colunas_data = ['data_primeira_compra', 'data_ultima_compra','data_pedido']

for coluna in colunas_int:
    df[coluna] = df[coluna].replace({' ': ''}, regex=True)
    df[coluna] = pd.to_numeric(df[coluna], errors='coerce').astype('Int64')

for coluna in colunas_float:
    df[coluna] = df[coluna].replace({',': '.'}, regex=True)
    df[coluna] = df[coluna].replace({' ': ''}, regex=True)
    df[coluna] = pd.to_numeric(df[coluna], errors='coerce').astype(float)

for coluna in colunas_data:
    df[colunas_data] = df[colunas_data].replace(r'\s+', '', regex=True)
    df[coluna] = pd.to_datetime(df[coluna], errors='coerce',format='%Y-%m-%d')

In [60]:
df

,id_pedido,id_cliente,nome_cliente,segmento_cliente,tipo_cliente,data_primeira_compra,data_ultima_compra,id_produto,nome_produto,categoria,...,percentual_desconto,canal_venda,metodo_pagamento,representante_vendas,regiao,despesas_operacionais,saldo_caixa,saldo_divida,gasto_mensal,indicador_churn
0,10001,C1689,Thiago Alves,Consumer,New,2023-08-26,2024-04-24,P1001,MX Keys S,Electronics,...,0.05,Online,Credit Card,Eduardo,South,239.83,14629.23,3092.03,329.57,0
1,10002,C1002,Juliana Araújo,Consumer,New,2023-02-26,2025-07-15,P1002,Redmi Note 13,Electronics,...,0.15,Online,Credit Card,Diego,North,81.55,8719.54,1189.63,88.62,1
2,10003,C1422,Igor Costa,Consumer,New,2023-03-10,2024-01-01,P1003,iPad mini,Electronics,...,0.15,Online,Cash,Camila,South,244.79,9475.50,3302.27,389.89,0
3,10004,C1308,João Silva,Consumer,New,2023-10-02,2024-01-17,P1004,Galaxy S24,Electronics,...,0.00,Retail,Credit Card,Camila,West,304.91,12381.10,122.53,306.67,0
4,10005,C0826,Vanessa Araújo,Consumer,New,2023-11-04,2024-12-17,P1002,Redmi Note 13,Electronics,...,0.05,Online,Credit Card,Eduardo,Central,24.90,12661.78,2031.60,317.36,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,16996,C1164,Ana Rocha,Consumer,Returning,2022-11-25,2025-10-06,P1014,WH-1000XM5,Electronics,...,0.05,Online,Credit Card,Bruno,South,44.92,9181.03,0.00,378.89,0
6996,16997,C1555,Gabriel Silva,Consumer,Returning,2022-10-17,2025-12-10,P1034,iPhone 15 Plus,Electronics,...,0.10,Online,Credit Card,Diego,South,244.44,15611.15,2000.66,427.75,0
6997,16998,C1169,Patrícia Gomes,Consumer,Returning,2023-06-05,2025-07-22,P1027,320K Keyboard,Electronics,...,0.10,Retail,Credit Card,Bruno,South,143.83,17857.85,4046.86,321.57,0
6998,16999,C1374,Ana Souza,Consumer,Returning,2023-06-11,2025-10-28,P1030,Flip 6,Electronics,...,0.00,Online,Debit Card,Camila,East,283.17,16181.14,3545.08,386.07,0
6999,17000,C1455,Renato Souza,SMB,Returning,2023-02-15,2025-11-18,P1028,Galaxy Tab S9,Electronics,...,0.20,Online,Debit Card,Camila,East,77.62,8758.22,5578.31,437.83,1

#### Vendas

In [86]:
f_vendas = df[['id_pedido', 'id_cliente', 'data_primeira_compra', 'data_ultima_compra',
       'id_produto','data_pedido', 'quantidade', 'preco_unitario', 'percentual_desconto',
       'canal_venda', 'metodo_pagamento', 'representante_vendas', 'regiao',
       'despesas_operacionais', 'saldo_caixa', 'saldo_divida', 'gasto_mensal',
       'indicador_churn']].copy()

f_vendas['mes'] = f_vendas['data_pedido'].dt.month.astype('string')
f_vendas['ano'] = f_vendas['data_pedido'].dt.year.astype('string')
f_vendas['trimestre'] = f_vendas['data_pedido'].dt.quarter.astype('string')
f_vendas

,id_pedido,id_cliente,data_primeira_compra,data_ultima_compra,id_produto,data_pedido,quantidade,preco_unitario,percentual_desconto,canal_venda,...,representante_vendas,regiao,despesas_operacionais,saldo_caixa,saldo_divida,gasto_mensal,indicador_churn,mes,ano,trimestre
0,10001,C1689,2023-08-26,2024-04-24,P1001,2024-04-24,4,109.77,0.05,Online,...,Eduardo,South,239.83,14629.23,3092.03,329.57,0,4,2024,2
1,10002,C1002,2023-02-26,2025-07-15,P1002,2025-07-15,3,350.29,0.15,Online,...,Diego,North,81.55,8719.54,1189.63,88.62,1,7,2025,3
2,10003,C1422,2023-03-10,2024-01-01,P1003,2024-01-01,2,643.98,0.15,Online,...,Camila,South,244.79,9475.50,3302.27,389.89,0,1,2024,1
3,10004,C1308,2023-10-02,2024-01-17,P1004,2024-01-17,1,844.50,0.00,Retail,...,Camila,West,304.91,12381.10,122.53,306.67,0,1,2024,1
4,10005,C0826,2023-11-04,2024-12-17,P1002,2024-12-17,1,332.72,0.05,Online,...,Eduardo,Central,24.90,12661.78,2031.60,317.36,0,12,2024,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,16996,C1164,2022-11-25,2025-10-06,P1014,2025-02-06,2,323.90,0.05,Online,...,Bruno,South,44.92,9181.03,0.00,378.89,0,2,2025,1
6996,16997,C1555,2022-10-17,2025-12-10,P1034,2025-06-04,1,1151.16,0.10,Online,...,Diego,South,244.44,15611.15,2000.66,427.75,0,6,2025,2
6997,16998,C1169,2023-06-05,2025-07-22,P1027,2025-07-22,4,37.02,0.10,Retail,...,Bruno,South,143.83,17857.85,4046.86,321.57,0,7,2025,3
6998,16999,C1374,2023-06-11,2025-10-28,P1030,2024-01-05,3,125.19,0.00,Online,...,Camila,East,283.17,16181.14,3545.08,386.07,0,1,2024,1
6999,17000,C1455,2023-02-15,2025-11-18,P1028,2024-10-26,1,833.29,0.20,Online,...,Camila,East,77.62,8758.22,5578.31,437.83,1,10,2024,4

### ESTRUTURA ESTRELA

#### Região / Vendedores

In [65]:
d_vendedores = (
    df[['representante_vendas','regiao']]
    .drop_duplicates(subset='representante_vendas', keep='first')
    .reset_index(drop=True)
)
d_vendedores

  representante_vendas regiao
0              Eduardo  South
1                Diego  North
2               Camila  South
3                  Ana   West
4                Bruno  North

#### Produtos

In [62]:
d_produtos = (
    df[['id_produto','nome_produto','categoria','subcategoria','marca']]
    .drop_duplicates(subset='id_produto', keep='first')
    .reset_index(drop=True)
)
d_produtos

   id_produto        nome_produto    categoria subcategoria     marca
0       P1001           MX Keys S  Electronics  Peripherals  Logitech
1       P1002       Redmi Note 13  Electronics  Smartphones    Xiaomi
2       P1003           iPad mini  Electronics      Tablets     Apple
3       P1004          Galaxy S24  Electronics  Smartphones   Samsung
4       P1005       Latitude 5440  Electronics      Laptops      Dell
5       P1006           iPhone 15  Electronics  Smartphones     Apple
6       P1007           iPhone 14  Electronics  Smartphones     Apple
7       P1008        HomePod mini  Electronics        Audio     Apple
8       P1009            iPad Air  Electronics      Tablets     Apple
9       P1010            Brio 500  Electronics  Peripherals  Logitech
10      P1011             Poco X6  Electronics  Smartphones    Xiaomi
11      P1012      MacBook Air M3  Electronics      Laptops     Apple
12      P1013          WF-1000XM5  Electronics        Audio      Sony
13      P1014          WH-1000XM5  Electronics        Audio      Sony
14      P1015           IdeaPad 5  Electronics      Laptops    Lenovo
15      P1016      MacBook Air M2  Electronics      Laptops     Apple
16      P1017            Charge 5  Electronics        Audio       JBL
17      P1018      MacBook Pro 14  Electronics      Laptops     Apple
18      P1019        ThinkPad E14  Electronics      Laptops    Lenovo
19      P1020       Legion Slim 5  Electronics      Laptops    Lenovo
20      P1021          Tune 770NC  Electronics        Audio       JBL
21      P1022              XPS 13  Electronics      Laptops      Dell
22      P1023          Galaxy A55  Electronics  Smartphones   Samsung
23      P1024    Galaxy Tab S9 FE  Electronics      Tablets   Samsung
24      P1025       USB-C Dock G5  Electronics  Peripherals        HP
25      P1026         Inspiron 15  Electronics      Laptops      Dell
26      P1027       320K Keyboard  Electronics  Peripherals        HP
27      P1028       Galaxy Tab S9  Electronics      Tablets   Samsung
28      P1029      Galaxy Tab A9+  Electronics      Tablets   Samsung
29      P1030              Flip 6  Electronics        Audio       JBL
30      P1031           Xiaomi 14  Electronics  Smartphones    Xiaomi
31      P1032       DeathAdder V3  Electronics  Peripherals     Razer
32      P1033           SRS-XB100  Electronics        Audio      Sony
33      P1034      iPhone 15 Plus  Electronics  Smartphones     Apple
34      P1035    Galaxy S24 Ultra  Electronics  Smartphones   Samsung
35      P1036         AirPods Pro  Electronics        Audio     Apple
36      P1037           AirPods 3  Electronics        Audio     Apple
37      P1038            M10 Plus  Electronics      Tablets    Lenovo
38      P1039  235 Wireless Mouse  Electronics  Peripherals        HP
39      P1040            Kiyo Pro  Electronics  Peripherals     Razer
40      P1041             Tab P12  Electronics      Tablets    Lenovo
41      P1042        MX Master 3S  Electronics  Peripherals  Logitech
42      P1043       BlackWidow V4  Electronics  Peripherals     Razer
43      P1044       iPad 10th Gen  Electronics      Tablets     Apple
44      P1045         Tab Extreme  Electronics      Tablets    Lenovo

#### Clientes

In [61]:
d_clientes = (
    df[['id_cliente','nome_cliente','segmento_cliente','tipo_cliente']]
    .drop_duplicates(subset='id_cliente', keep='first')
    .reset_index(drop=True)
)
d_clientes

     id_cliente      nome_cliente segmento_cliente tipo_cliente
0         C1689      Thiago Alves         Consumer          New
1         C1002    Juliana Araújo         Consumer          New
2         C1422        Igor Costa         Consumer          New
3         C1308        João Silva         Consumer          New
4         C0826    Vanessa Araújo         Consumer          New
...         ...               ...              ...          ...
1722      C1386     Aline Pereira         Consumer          New
1723      C0564  Beatriz Oliveira         Consumer          New
1724      C0052    Thiago Martins        Corporate          New
1725      C1094    Renato Martins         Consumer          New
1726      C1366      João Ribeiro         Consumer          New

[1727 rows x 4 columns]